### PR TITLE
Try out a Cargo workspace for wasm/ directory

### PR DESCRIPTION
**Pull request by james-chf**
Relates to anoma/namada#102

If this works, we could later include `wasm_for_tests/` in it

### CODE REVIEW

**Comment by james-chf** [comment]
pls update wasm

**Comment by juped** [comment]
I forget why this didn't work at the time exactly, but see also 5f77939bfcadac660f8854111ecb5ea3dd1524de

**Comment by james-chf** [comment]
pls update wasm

**Comment by james-chf** [comment]
pls update wasm

**Comment by james-chf** [comment]
I rebased this branch onto `v0.5.0`

**Comment by james-chf** [comment]
Force pushed a rebase onto v0.6.0

**Comment by james-chf** [comment]
pls update wasm

**Comment by tzemanovic** [comment]
I think this is good and we can use it - it prevents having a separate target dir for each wasm crate. I agree to also include `wasm_for_tests`.

| I forget why this didn't work at the time exactly, but see also https://github.com/anoma/anoma/commit/5f77939bfcadac660f8854111ecb5ea3dd1524de
I think there's an issue with the wasm being cdylib crates

**Comment by tzemanovic** [comment]
moved to https://github.com/anoma/namada/pull/258

**Pull request closed without merging**
