### PR TITLE
Use IBC messages

### LINKED ISSUE #699: Use IBC messages of ibc-rs
Currently, we use `*Data` types for IBC-related transactions as transaction data.
We can use messages (e.g. https://github.com/informalsystems/ibc-rs/tree/master/modules/src/core/ics02_client/msgs) of ibc-rs by adding borsh serialization/deserialization so that an IBC relayer can submit a transaction with the message type.

### PR DESCRIPTION
**Pull request by yito88**
closes #699 (after #656)

### CODE REVIEW

**Comment by yito88** [comment]
pls update wasm

**Comment by yito88** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Comment by Fraccaman** [comment]
pls update wasm

**Review by tzemanovic — APPROVED** [review]
LGTM, thanks! I'll rebase and add changelog

**Comment by tzemanovic** [comment]
pls update wasm

**Pull request merged**
