### PR TITLE
cli: allow specifying an absolute ANOMA_WASM_DIR

### PR DESCRIPTION
**Pull request by james-chf**
Relates to https://github.com/anoma/namada/issues/136

### CODE REVIEW

**Comment by james-chf** [comment]
https://github.com/anoma/anoma/issues/1048 tripped me up again. I was trying to run `anomac init-account` without having run `anoman ledger` at least once.

**Comment by tzemanovic** [comment]
Nice, I agree it's better to allow this. I think we can also remove the check from `client utils join-network`:

```diff
--- a/apps/src/lib/client/utils.rs
+++ b/apps/src/lib/client/utils.rs
@@ -131,15 +131,6 @@ pub async fn join_network(
             None
         }
     });
-    if let Some(wasm_dir) = wasm_dir.as_ref() {
-        if wasm_dir.is_absolute() {
-            eprintln!(
-                "The arg `--wasm-dir` cannot be an absolute path. It is \
-                 nested inside the chain directory."
-            );
-            cli::safe_exit(1);
-        }
-    }
 
     let release_filename = format!("{}.tar.gz", chain_id);
     let release_url = format!(
```

As this still works with absolute path. 

However, I'm not sure about `init-network` - it seems that any validators created by it would need to have the `wasm_dir` updated to their config or perhaps better, we should just use the default WASM dir path for validator setup:

```diff
--- a/apps/src/lib/client/utils.rs
+++ b/apps/src/lib/client/utils.rs
@@ -749,26 +740,6 @@ pub fn init_network(
     let genesis_path = global_args
         .base_dir
         .join(format!("{}.toml", chain_id.as_str()));
-    let wasm_dir = global_args
-        .wasm_dir
-        .as_ref()
-        .cloned()
-        .or_else(|| {
-            if let Ok(wasm_dir) = env::var(ENV_VAR_WASM_DIR) {
-                let wasm_dir: PathBuf = wasm_dir.into();
-                Some(wasm_dir)
-            } else {
-                None
-            }
-        })
-        .unwrap_or_else(|| config::DEFAULT_WASM_DIR.into());
-    if wasm_dir.is_absolute() {
-        eprintln!(
-            "The arg `--wasm-dir` cannot be an absolute path. It is nested \
-             inside the chain directory."
-        );
-        cli::safe_exit(1);
-    }
 
     // Write the genesis file
     genesis_config::write_genesis_config(&config_clean, &genesis_path);
@@ -784,15 +755,6 @@ pub fn init_network(
     // Rename the generate chain config dir from `temp_chain_id` to `chain_id`
     fs::rename(&temp_dir, &chain_dir).unwrap();
 
-    // Copy the WASM checksums
-    let wasm_dir_full = chain_dir.join(&wasm_dir);
-    fs::create_dir_all(&wasm_dir_full).unwrap();
-    fs::copy(
-        &wasm_checksums_path,
-        wasm_dir_full.join(config::DEFAULT_WASM_CHECKSUMS_FILE),
-    )
-    .unwrap();
-
     config.validator.iter().for_each(|(name, _config)| {
         let validator_dir = global_args
             .base_dir
@@ -811,7 +773,7 @@ pub fn init_network(
             .unwrap();
 
         // Copy the WASM checksums
-        let wasm_dir_full = validator_chain_dir.join(&wasm_dir);
+        let wasm_dir_full = validator_chain_dir.join(&config::DEFAULT_WASM_DIR);
         fs::create_dir_all(&wasm_dir_full).unwrap();
         fs::copy(
             &wasm_checksums_path,
```

**Comment by james-chf** [comment]
Thanks for reviewing @tzemanovic, I made the changes from your comment. Yeah I guess `ANOMA_WASM_DIR` doesn't make sense in the context of `init-network` when generating directories for each test validator, using a default wasm directory for each test validator seems straightforward

**Comment by james-chf** [comment]
I had to add back copying wasm checksums for every validator directory, then CI passes

**Comment by tzemanovic** [comment]
moved to https://github.com/anoma/namada/pull/263

**Pull request closed without merging**
