### PR TITLE
Changed hash-map to BiHashMap 

### PR DESCRIPTION
**Pull request by bengtlofgren**
In the wallet in order to be able to retrieve alias from address.

I think this is a good idea for UI, since atm we are spitting out hashed addresses that we don't know correspond to any account

### CODE REVIEW

**Comment by tzemanovic** [comment]
nice! there's #472 for this :)

**Comment by brentstone** [comment]
I'm wondering if changing to BiHashMap is even needed... is there a way to convert the `address` into a `PublicKeyHash` and then use `Store::pkhs` HashMap to get the `alias`?

**Comment by james-chf** [comment]
> I'm wondering if changing to BiHashMap is even needed... is there a way to convert the `address` into a `PublicKeyHash` and then use `Store::pkhs` HashMap to get the `alias`?

Commenting here based on discussion earlier - the bech32m address (e.g. `atest1v4ehgw36g56ngwpk8ppnzsf4xqeyvsf3xq6nxde5gseyys3nxgenvvfex5cnyd2rx9zrzwfctgx7sp`) is derived from the "hash" of an account, for an implicit account this "hash" is the `PublicKeyHash` but for established accounts it's something random, I think using the `BiHashMap` here should be the most straightforward option

**Comment by tzemanovic** [comment]
I rebased the branch onto v0.6.1 to check CI

**Comment by tzemanovic** [comment]
moved to https://github.com/anoma/namada/pull/264

**Pull request closed without merging**
