### PR TITLE
IBC FungibleTransferToken follow-up

### PR DESCRIPTION
**Pull request by tzemanovic**
follow-up to #820, this PR:

* adds `tx::write_temp` and `vp::read_temp` to the ledger. This is used in IBC fungible token transfer tx instead of filtering out write log on commit by the storage keys and read by the IBC VP
* fixes and refactors IBC token VP

These are the commits from #820 that weren't merged to the last release

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762839801627) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by tzemanovic** [comment]
pls update wasm

**Comment by yito88** [comment]
Thank you for following up! LGTM

**Review by yito88 — APPROVED** [review]
Thank you for following up! LGTM

**Comment by tzemanovic** [comment]
bad bot

**Pull request merged**
