### PR TITLE
init-network create archive for anoma-network-config release

### PR DESCRIPTION
**Pull request by tzemanovic**
This PR adds tar.gz creation in `init-network` cmd that can be used to make a release for the anoma-network-config repo using a script from https://github.com/heliaxdev/anoma-network-config/pull/4. The command to `join-network` has been updated to then use the GH releases in https://github.com/anoma/anoma/pull/619

### CODE REVIEW

**Comment by tzemanovic** [comment]
We're using `init-network` for e2e tests, so running them creates the archives. I will update this to optionally skip creating archive and use the option in e2e tests

**Comment by juped** [comment]
force pushed this for our release candidate

**Comment by tzemanovic** [comment]
pls restart ci

**Comment by tzemanovic** [comment]
pls restart ci

**Pull request merged**
