### PR TITLE
Add EthBridge internal address

### PR DESCRIPTION
**Pull request by james-chf**
Relates to https://github.com/anoma/anoma/issues/1102

This branch is based off latest `master` (integrating with some changes since last release), will eventually rebase off of the next release (e.g. `v0.6.0`) before it merges

This PR adds
- `InternalAddress::EthBridge` with a VP which (currently) rejects any changes to its storage
- E2E test which verifies the EthBridge VP rejects an attempt to write to its `/queue`
- test wasm `tx_write_storage_key.wasm` used by the E2E test

### Testing
There is an e2e test to assert that no transaction can currently modify the EthBridge storage.

```shell
RUST_BACKTRACE=none ANOMA_E2E_KEEP_TEMP=true ANOMA_E2E_DEBUG=true cargo test \
    --features anoma_apps/ABCI \
    --package 'anoma_apps' \
    --package 'anoma_tests' \
    ethbridge -- \
        --test-threads=1 \
        --nocapture
```

### CODE REVIEW

**Comment by james-chf** [comment]
pls update wasm

**Comment by james-chf** [comment]
pls update wasm

**Comment by james-chf** [comment]
pls update wasm

**Review by batconjurer — APPROVED** [review]
LGTM

**Comment by james-chf** [comment]
thanks for reviewing, will leave this open to merge after next release

**Comment by james-chf** [comment]
pls update wasm

**Pull request merged**
