### PR TITLE
wallet: remove redundant clone()

### PR DESCRIPTION
**Pull request by juped**
The initial version of 'wallet: canonicalize all aliases to lowercase'
(ac3f0ba8e) was made against a less stringent clippy, and I failed
to check for new warnings when applying it. Rectify the redundant
clone warning.

### CODE REVIEW

**Comment by tzemanovic** [comment]
there are 3 e2e tests failing, I'll fix 'em up

**Comment by juped** [comment]
just need to downcase the command line arguments which can take aliases, i think (--signing-key is the only one in the tests i think, but there are others)

**Comment by tzemanovic** [comment]
> just need to downcase the command line arguments which can take aliases, i think (--signing-key is the only one in the tests i think, but there are others)

yeah, the lower-casing is in somewhat ad-hoc locations so it's kinda error prone. I'm trying to refactor it a bit to encapsulate the lower-casing behavior

**Comment by tzemanovic** [comment]
@juped Everything should be passing now

**Comment by tzemanovic** [comment]
I also renamed the default aliases in 7a50f56 to snake case to keep them readable in lowercase

**Pull request merged**
