### PR TITLE
Renamed all abci++ deps to abcipp for nix and giggles

### PR DESCRIPTION
**Pull request by batconjurer**
Renamed abci++ branches and deps to abcipp so that nix can properly parse urls. Also, some 3rd party updates had deprecated crap that needed updating to appease clippy.

### CODE REVIEW

**Review by SimSaladin — APPROVED** [review]

**Comment by batconjurer** [comment]
pls update ci

**Comment by batconjurer** [comment]
pls update wasm

**Comment by batconjurer** [comment]
pls update wasm

**Comment by batconjurer** [comment]
pls update wasms

**Comment by SimSaladin** [comment]
This is fixes the `Cargo.nix` generation via `crate2nix`. There's still a minor issue that `crate2nix` doesn't handle the `tendermint-proto`/`tendermint-proto-abci` (and other packages) renaming correctly behind feature flags (it uses the same source for both when it should use different branches).

This can be worked around by choosing one of `ABCI`, `ABCI-plus-plus` at generation time:

```bash
crate2nix generate --no-default-features --features "std ABCI"
```

And then building with the same flags:

```nix
cargo_nix.workspaceMembers.anoma_apps.build.override { features = ["std" "ABCI"]; }
```

**Pull request merged**
