### PR TITLE
Sign tx hash

### LINKED ISSUE #886: tx signatures - sign hashes
for tx signatures, only sign the hash of the tx bytes instead of the tx bytes

### PR DESCRIPTION
**Pull request by Fraccaman**
closes #886

### CODE REVIEW

**Review by batconjurer — COMMENTED** [review]
I don't see the modifications to the wrapper tx tests?

**Comment by Fraccaman** [comment]
> I don't see the modifications to the wrapper tx tests?

I think i just had to modify [this line](https://github.com/anoma/anoma/blob/9b1898c502d719797953e287947ae7938ed93b85/shared/src/types/key/ed25519.rs#L168)

**Review by batconjurer — APPROVED** [review]

**Review by tzemanovic — APPROVED** [review]
LGTM, thanks!

**Comment by tzemanovic** [comment]
pls update wasm

**Pull request merged**
